syntax = "proto3";

package payment;

option go_package = "github.com/nureeek/Generated-order-payment-grpc/payment";

import "google/protobuf/timestamp.proto";

service PaymentService {
  rpc ProcessPayment(PaymentRequest) returns (PaymentResponse);
  rpc ListPayments(ListPaymentsRequest) returns (ListPaymentsResponse);
}

message PaymentRequest {
  string order_id = 1;
  double amount = 2;
  string currency = 3;
}

message PaymentResponse {
  string payment_id = 1;
  string status = 2;
  google.protobuf.Timestamp created_at = 3;
  int64 amount = 4;
}

message ListPaymentsRequest {
  int64 min_amount = 1;
  int64 max_amount = 2;
}

message ListPaymentsResponse {
  repeated PaymentResponse payments = 1;
}